services:
  ai_translator_api:
    container_name: ai_translator_api
    restart: unless-stopped
    build:
      context: ./ai_translator_api
      dockerfile: Dockerfile.api.${ENV}
    image: ai_translator_api:latest
    env_file:
      - env/.api.env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app_network

  ai_translator_client:
    container_name: ai_translator_client
    restart: unless-stopped
    build:
      context: ./ai_translator_client
      dockerfile: Dockerfile.client.${ENV}
    image: ai_translator_client:latest
    env_file:
      - env/.api.env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - app_network

networks:
  app_network:
    name: "${ENV}_network"
    driver: bridge
